# Generated by Django 6.0.6 on 2026-06-04 21:24

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('contributor', 'Contributor'), ('admin', 'Admin')], default='buyer', max_length=20)),
                ('mpesa_phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(regex='^(\\+254|0)[17][0-9]{8}$')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('watermarked_preview_url', models.URLField(max_length=1000)),
                ('secure_raw_s3_key', models.CharField(max_length=1024)),
                ('sheng_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('formal_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('contributor', models.ForeignKey(db_column='contributor_id', on_delete=django.db.models.deletion.PROTECT, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mpesa_receipt_no', models.CharField(max_length=100, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contributor_cut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_cut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('buyer', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(db_column='photo_id', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='lenskenya.photo')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_pdf_url', models.URLField(max_length=1000)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(db_column='photo_id', on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='lenskenya.photo')),
                ('transaction', models.OneToOneField(db_column='transaction_id', on_delete=django.db.models.deletion.PROTECT, related_name='license', to='lenskenya.transaction')),
            ],
            options={
                'db_table': 'licenses',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['contributor'], name='photos_contributor_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['county'], name='photos_county_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sheng_tags'], name='photos_sheng_tags_gin'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['formal_tags'], name='photos_formal_tags_gin'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer'], name='transactions_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['photo'], name='transactions_photo_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transactions_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transactions_created_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gt', 0)), name='transactions_amount_paid_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('contributor_cut__gte', 0)), name='transactions_contributor_cut_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('platform_cut__gte', 0)), name='transactions_platform_cut_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid', django.db.models.expressions.CombinedExpression(models.F('contributor_cut'), '+', models.F('platform_cut')))), name='transactions_split_equals_amount_paid'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['photo'], name='licenses_photo_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['buyer'], name='licenses_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['issued_at'], name='licenses_issued_at_idx'),
        ),
    ]
