# Generated by Django 6.0.6 on 2026-06-04 21:50

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenskenya', '0002_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='photo',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['created_at'], name='photos_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['status', 'created_at'], name='photos_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['status', 'county'], name='photos_status_county_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('views'), '+', models.F('downloads')), '+', models.F('likes')), name='photos_popularity_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='photos_tags_gin'),
        ),
    ]
