# Generated by Copilot for the updated public API contract.

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('lenskenya', '0003_photo_downloads_photo_likes_photo_status_photo_tags_and_more'),
	]

	operations = [
		migrations.AddField(
			model_name='user',
			name='name',
			field=models.CharField(blank=True, default='', max_length=255),
		),
		migrations.AddField(
			model_name='photo',
			name='county_code',
			field=models.PositiveSmallIntegerField(blank=True, null=True),
		),
		migrations.AddField(
			model_name='photo',
			name='license_type',
			field=models.CharField(choices=[('Free_Attribution', 'Free Attribution'), ('Commercial_Paid', 'Commercial Paid')], default='Free_Attribution', max_length=30),
		),
		migrations.AddField(
			model_name='photo',
			name='price_kes',
			field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
		),
		migrations.AlterField(
			model_name='photo',
			name='status',
			field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('processing', 'Processing')], default='pending', max_length=20),
		),
		migrations.AlterField(
			model_name='photo',
			name='watermarked_preview_url',
			field=models.URLField(blank=True, max_length=1000, null=True),
		),
		migrations.AddIndex(
			model_name='photo',
			index=models.Index(fields=['county_code'], name='photos_county_code_idx'),
		),
		migrations.AddIndex(
			model_name='photo',
			index=models.Index(fields=['license_type'], name='photos_license_type_idx'),
		),
	]