# Generated by Django 6.0.6 on 2026-06-04 23:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenskenya', '0004_user_name_photo_county_code_photo_license_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='contributor',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='county',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='downloads',
            field=models.PositiveIntegerField(db_column='clicks', default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='secure_raw_s3_key',
            field=models.CharField(db_column='raw_secure_file', max_length=1024),
        ),
        migrations.AlterField(
            model_name='photo',
            name='watermarked_preview_url',
            field=models.URLField(blank=True, db_column='watermarked_preview', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='refresh_token_id',
            field=models.UUIDField(db_column='instance_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='mpesa_phone',
            field=models.CharField(blank=True, db_column='phone_number', max_length=13, null=True, validators=[django.core.validators.RegexValidator(regex='^(\\+254|0)[17][0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='password', max_length=128),
        ),
    ]
