# Generated by Django 6.0.6 on 2026-06-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenskenya', '0006_remove_user_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='camera',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['category'], name='photos_category_idx'),
        ),
    ]
