# Generated by Django 6.0.6 on 2026-06-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenskenya', '0007_photo_camera_photo_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('contributor', 'Contributor'), ('admin', 'Admin')], default='contributor', max_length=20),
        ),
    ]
